name: select2dot1
description: Select2dot1 give you a fully customizable single/multiple select box with support for searching, group option, extra info and avatar. Works using overlay and modal.
version: 2.0.7
homepage: https://select2dot1.site
repository: https://github.com/romanjrdykyj/select2dot1
issue_tracker: https://github.com/romanjrdykyj/select2dot1/issues
screenshots:
  - description: 'This screenshot shows Select2dot1 in mobile version'
    path: img/mobile_example.webp
  - description: 'This screenshot shows Select2dot1 in desktop version'
    path: img/desktop_example.webp

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies: 
  flutter: 
    sdk: flutter

dev_dependencies: 
  dart_code_metrics: ">=4.20.0 <6.0.0"
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  pubspec_dependency_sorter: ">=0.0.2 <2.0.0"

flutter:
